/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchenRouteImport } from './routes/branchen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as VorgehenRouteImport } from './routes/vorgehen'
import { Route as KarriereIndexRouteImport } from './routes/karriere.index'
import { Route as KarriereSlugRouteImport } from './routes/karriere.$slug'
import { Route as KarriereBewerbungRouteImport } from './routes/karriere.bewerbung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchenRoute = BranchenRouteImport.update({
  id: '/branchen',
  path: '/branchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const VorgehenRoute = VorgehenRouteImport.update({
  id: '/vorgehen',
  path: '/vorgehen',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereIndexRoute = KarriereIndexRouteImport.update({
  id: '/karriere/',
  path: '/karriere/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereSlugRoute = KarriereSlugRouteImport.update({
  id: '/karriere/$slug',
  path: '/karriere/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereBewerbungRoute = KarriereBewerbungRouteImport.update({
  id: '/karriere/bewerbung',
  path: '/karriere/bewerbung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branchen': typeof BranchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vorgehen': typeof VorgehenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branchen': typeof BranchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vorgehen': typeof VorgehenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere': typeof KarriereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branchen': typeof BranchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vorgehen': typeof VorgehenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branchen'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/ueber-uns'
    | '/vorgehen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branchen'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/ueber-uns'
    | '/vorgehen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere'
  id:
    | '__root__'
    | '/'
    | '/branchen'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/ueber-uns'
    | '/vorgehen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchenRoute: typeof BranchenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  TeamRoute: typeof TeamRoute
  UeberUnsRoute: typeof UeberUnsRoute
  VorgehenRoute: typeof VorgehenRoute
  KarriereSlugRoute: typeof KarriereSlugRoute
  KarriereBewerbungRoute: typeof KarriereBewerbungRoute
  KarriereIndexRoute: typeof KarriereIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branchen': {
      id: '/branchen'
      path: '/branchen'
      fullPath: '/branchen'
      preLoaderRoute: typeof BranchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorgehen': {
      id: '/vorgehen'
      path: '/vorgehen'
      fullPath: '/vorgehen'
      preLoaderRoute: typeof VorgehenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/': {
      id: '/karriere/'
      path: '/karriere'
      fullPath: '/karriere/'
      preLoaderRoute: typeof KarriereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/$slug': {
      id: '/karriere/$slug'
      path: '/karriere/$slug'
      fullPath: '/karriere/$slug'
      preLoaderRoute: typeof KarriereSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/bewerbung': {
      id: '/karriere/bewerbung'
      path: '/karriere/bewerbung'
      fullPath: '/karriere/bewerbung'
      preLoaderRoute: typeof KarriereBewerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchenRoute: BranchenRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  TeamRoute: TeamRoute,
  UeberUnsRoute: UeberUnsRoute,
  VorgehenRoute: VorgehenRoute,
  KarriereSlugRoute: KarriereSlugRoute,
  KarriereBewerbungRoute: KarriereBewerbungRoute,
  KarriereIndexRoute: KarriereIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
